name: Node.js CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      node_version: ${{ steps.nvm.outputs.NVMRC }}
    steps:
      - uses: actions/checkout@v3
      - name: Read .nvmrc
        id: nvm
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT

  test:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test_type:
          - unit
          - nestjs
          - mocha
    steps:
      - uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ needs.prepare.outputs.node_version }}

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modulos
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: List the state of node modules
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        continue-on-error: true
        run: npm ci

      - name: Run ${{ matrix.test_type }} tests
        run: |
          case "${{ matrix.test_type }}" in
            "unit")
              npm test
              ;;
            "nestjs")
              npm run test:nestjs
              ;;
            "mocha")
              npm run test:mocha
              ;;
          esac