name: Node.js CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      node_version: ${{ steps.nvm.outputs.NVMRC }}
    steps:
      - uses: actions/checkout@v3
      - name: Read .nvmrc
        id: nvm
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT

  test:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test_type:
          - unit
          - nestjs
          - mocha
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ needs.prepare.outputs.node_version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ${{ matrix.test_type }} tests
        run: |
          case "${{ matrix.test_type }}" in
            "unit")
              npm test
              ;;
            "nestjs")
              npm run test:nestjs
              ;;
            "mocha")
              npm run test:mocha
              ;;
          esac